apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::805431668682:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-XR7SLGSO340B
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::805431668682:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-27T12:03:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1732"
  uid: 78d0cb0a-03c2-4221-b7e5-fd4aca5f5764
